version: "3.8"

services:
  # 1. El nuevo corazón: SQL Server (MSSQL)
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: raven_mssql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=RavenAdmin2026! # 👈 Contraseña fuerte obligatoria
      - MSSQL_PID=Developer # Versión completa y gratuita para desarrollo
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  # 2. El motor de alta velocidad: Redis (Para validar QRs)
  redis_raven:
    image: redis:alpine
    container_name: raven_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  sqlserver_data:
  redis_data:
