version: '3.8'

services:
  db_postgres:
    image: postgres:15-alpine
    container_name: postgres_credenciales
    restart: always
    environment:
      POSTGRES_USER: RavenAdmin
      POSTGRES_PASSWORD: Kaoriko2
      POSTGRES_DB: sistema_qr
    ports:
      - "5432:5432"
    volumes:
      # Sincroniza el script de inicialización
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # Persistencia de datos en tu Machenike
      - pgdata:/var/lib/postgresql/data

  cache_redis:
    image: redis:alpine
    container_name: redis_credenciales
    restart: always
    ports:
      - "6379:6379"

  panel_adminer:
    image: adminer
    container_name: adminer_credenciales
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db_postgres

volumes:
  pgdata: